# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check (lint + security)

on:

  push:
    branches: [ main, master, dev ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]

jobs:

  Check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --exclude setup.py . --count --select=E9,F63,F7,F82 --ignore=E272,E501,E266,E241,E226,E251,E303,E221 --exit-zero --max-complexity=10 --max-line-length=127 --show-source --statistics
#        continue-on-error: true
      - name: Install bandit
        run: pip install bandit
      - name: Check security issues with bandit
        run: bandit .
#        continue-on-error: true
